import localFont from "next/font/local";
import Navbar from "../navbar";
import { AppProvider } from "@/context/appContext";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "AI Plugin Galaxy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <AppProvider> */}
        <Navbar/>
        <Toaster position="top-center"/>
        {children}
        {/* </AppProvider> */}
      </body>
    </html>
  );
}
